- name: install ozone
  hosts: all
  become: true

  tasks:

  - name: Ensure linux group "hadoop" exists
    group:
      name: hadoop
      state: present
  - name: Add the user 'ozone' with a primary group of 'hadoop'
    user:
      name: ozone
      group: hadoop	       
  - name: create install folder
    file:
      path: /hadoop/app/ozone
      state: directory
      group: hadoop
      mode: '0775'
  - name: create data folder for ozone
    file:
      path: /hadoop/ozone/data
      state: directory
      group: hadoop
      mode: '0775'
  - name: create install folder
    file:
      path: /hadoop/app/ozone/data
      state: directory
      group: hadoop
      mode: '0775'
  - name: Download ozone
    get_url:
      url: https://downloads.apache.org/ozone/1.2.0/ozone-1.2.0.tar.gz
      dest: /hadoop/app/ozone/hadoop-ozone-1.2.0.tar.gz
      mode: '0775'
      
  - name: Extract Ozone jar
    unarchive:
      src: /hadoop/app/ozone/hadoop-ozone-1.2.0.tar.gz
      dest: /hadoop/app/ozone/
      remote_src: yes
      mode: '0775'
      group: hadoop
      extra_opts: [--strip-components=1]

  - name: Set Ozone for everyone in path
    lineinfile:
      path: /etc/profile
      line: 'export PATH=/hadoop/app/ozone/bin:$PATH' 

  - name: Change ozone script to source /etc/profile
    lineinfile:
      path: /hadoop/app/ozone/bin/ozone
      line: 'source /etc/profile'
      insertafter: .*bash\n

  - name: Copy ozone scripts
    copy:
      src: ./ozone/scripts/
      dest: /hadoop/app/ozone/bin/
      owner: ozone
      group: hadoop
      mode: '0754'

  - name: Copy ozone-site.xml
    copy:
      src: ./ozone/config/ozone-site.xml
      dest: /hadoop/app/ozone/etc/hadoop/ozone-site.xml
      owner: ozone
      group: hadoop
      mode: '0644'


- import_playbook: set_linux_config.yml      
- import_playbook: ozone_init_start_scm.yml
- import_playbook: ozone_init_start_om.yml
- import_playbook: ozone_start_datanode.yml
- import_playbook: ozone_start_s3g.yml
- import_playbook: ozone_start_recon.yml
